### ISSUE TITLE
Problem with running the grammar

### ISSUE THREAD

**Issue by loziniak** [Oldes/highlightjs-redbol#3]
There is a problem with running this grammar plugin with Exercism:

https://github.com/exercism/website/pull/6802

@Oldes can you help with that?

**Comment by dem4ron** [comment]
Hi!

We are trying to add syntax highlighting for Red on Exercism.

The main issue we've encountered while integrating this library is that it expects `hljs` to be in the global scope, which is not ideal in our case because we have put a lot of effort into importing highlight.js only when it is absolutely necessary.

We have also built some functionality on top of highlight.js and we need a modular setup for that - where we can explicitly register a language.

Would you please consider releasing another version where the library only exports the grammar definition in a modular way?

Thanks!

**Comment by Oldes** [comment]
Unfortunately I am not too familiar with modern JS and its packaging methods, so I am not sure what exactly you need from me. Isn't current version compatible with [this usage](https://highlightjs.org/#usage)?

**Comment by dem4ron** [comment]
Hi!
What we'd need is a version where only the `LanguageFn` - `function rebol` - is exported, like [here in the case of the javascript LanguageFn](https://github.com/highlightjs/highlight.js/blob/main/src/languages/javascript.js).

In the current case of `highlightjs-redbol`, the `LanguageFn` is wrapped in two IIFEs, one of which does the registering of the grammar, which we'd prefer to do manually.

**Comment by Oldes** [comment]
What I don't know is how to distribute it... for example when I check the [usage examples](https://github.com/highlightjs/highlight.js?tab=readme-ov-file#fetch-via-cdn), I can see, that used `go` lang is there used in two ways:
1. as a [plain js](https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/languages/go.min.js) (which is what I have now)
2.  and also as an [ES module](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/es/languages/go.min.js).

If I update my [NPM package](https://www.npmjs.com/package/highlightjs-redbol), wouldn't it brake something somewhere?

**Comment by Oldes** [comment]
It is now as en ES6 Module: https://github.com/Oldes/highlightjs-redbol/commit/50b69bb4cb39bbe63a558110ef94185f729c349b

So now there is the old Common JS version: https://unpkg.com/highlightjs-redbol@2.1.1/dist/redbol.min.js
and the module one: https://unpkg.com/highlightjs-redbol@2.1.1/dist/redbol.es.min.js

Hope you can use it somehow.

**Comment by dem4ron** [comment]
Thank you, this works!

Cheers.

**Comment by dem4ron** [comment]
One last thing - if you don't use a bundler, could you please export it using only CommonJS? 

The main problem wasn't with using CommonJS, but wrapping it in IIFEs, and self-registering the language function.

The Javascript language function that I linked in was using ES6 syntax, because they use rollup under the hood - sorry for not pointing this out.

What would be ideal is

``` Javascript
function redbol(hljs) {
...
}
module.exports = redbol
```

Thank you very much.

**Comment by Oldes** [comment]
Like this? https://github.com/Oldes/highlightjs-redbol/blob/master/src/languages/redbol.js

**Comment by dem4ron** [comment]
Yes, this looks good! Thanks for the effort!
